version: 2

sources:
  - name: ringcentral
    schema: source
    tables:
      - name: company_call_log
        identifier: ringcentral_Company_Call_Log
      - name: call_queues
        identifier: ringcentral_Call_Queue

models:
  - name: stg_ringcentral_company_call_log
  - name: stg_ringcentral_call_queues
