version: 2

sources:
  - name: ringcentral
    schema: source
    tables:
      - name: company_call_log
        identifier: ringcentral_Company_Call_Log

models:
  - name: stg_ringcentral_company_call_log
